# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f3d69154e0f8668c950b146e617548b32abb18c46d5dc041a49474dac28d9b4f57aa5459de42d082975ec2715bfbcad07a948d8934fd16f575cda8c96fb8542

test:
  secret_key_base: 3c79c6b2af7ac34cc504d3172675597f15ff867ae02c8954c2d7efdb072d5903f1ac7e8a511d8e7c92c072531215af6f5426c609f76741a3cfdfb6a08ae5ecd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
